export const ToolLost = [
    {
        link: "http://www.wanandroid.com/tools/bejson",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/bejson.png",
        title: "Json格式化转Bean",
        content: "支持JSON格式化，JSON转Java类，树形展示等",
    },
    {
        link: "http://www.wanandroid.com/tools/todo",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "todo",
        content: "在线的清单，帮你记录灵感，统计已经做完的事情。",
    },
    {
        link: "http://www.wanandroid.com/openapis",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "OpenApis",
        content: "收集的开放 API",
    },
    {
        link: "http://www.wanandroid.com/tools/digit",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/md5.png",
        title: "MD5,SHA等数字摘要",
        content: "支持MD5,SHA1,SHA224,SHA256,SHA384,SHA512在线转化",
    },
    {
        link: "http://www.wanandroid.com/maven_pom/index",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "Google仓库查询",
        content: "Google仓库查询",
    },
    {
        link: "http://www.wanandroid.com/tools/base64",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/base64.png",
        title: "Base64转化",
        content: "支持字符串、图文、文件等base64在线计算",
    },
    {
        link: "http://www.wanandroid.com/tools/decode",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "url decode",
        content: "url decode / encode 操作",
    },
    {
        link: "http://www.wanandroid.com/tools/qrcode",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/qrcode.png",
        title: "二维码生成",
        content: "支持二维码在线生成，支持个性化二维码",
    },
    {
        link: "http://www.wanandroid.com/tools/color",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/color.png",
        title: "取色器",
        content: "支持在线取色，颜色转化",
    },
    {
        link: "http://www.wanandroid.com/blog/show/2791",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "Android 版本",
        content: "Android 版本与 Version Code 对应。",
    },
    {
        link: "http://www.iconfont.cn/",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "iconfont你值得拥有",
        content: "图标查找",
    },
    {
        link: "https://tinypng.com/",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/tinypng.png",
        title: "tinypng压缩图片",
        content: "图片压缩",
    },
    {
        link: "http://www.wanandroid.com/tools/decimal",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/decimal.png",
        title: "进制转化",
        content: "支持常见进制转换，各种进制互转2转32以内，32以内转32以内",
    },
    {
        link: "http://dwz.cn/",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "短链接",
        content: "支持长连接转化为短链接",
    },
    {
        link: "http://www.wanandroid.com/article/list/0?cid=398",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "速查表",
        content: "速查表",
    },
    {
        link: "http://tool.oschina.net/regex",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "正则",
        content: "正则表达式",
    },
    {
        link: "http://t.codekk.com/url-order",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "URL按序解析",
        content: "有一长串复杂的URL？输入解析一下，一目了然~",
    },
    {
        link: "http://www.wanandroid.com/tools/ide",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "下载Studio 3.0.1",
        content: "搭建环境，下载Android Studo、SDK、NDK；版本分布；屏幕尺寸和分布；",
    },
    {
        link: "https://www.upyun.com/https",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/ide.png",
        title: "https安全检测",
        content: "https安全检测",
    },
    {
        link: "http://www.wanandroid.com/lg/userdraft/show",
        imgUrl: "https://www.wanandroid.com/resources/image/pc/tools/bejson.png",
        title: "草稿记事",
        content: "支持markdown，可以用来临时记录一些笔记。",
    },
];
